baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Getting Started Guide'

[module]
  [[module.imports]]
    path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[params]
  description = 'A step-by-step guide to setting up Hugo'
